"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, FileText, Globe2, LoaderCircle, Mic, Search, Sparkles, UploadCloud, X } from "lucide-react";

type Result = {
  profile: { name: string; industry: string; audience: string; tone: string[]; values: string[]; vocabulary: string[]; restricted: string[]; summary: string };
  competitors: { name: string; url: string; score: number; reason: string }[];
  stats: { pages: number; characters: number; chunks: number; vectors: number; vectorBackend?: "qdrant"|"fallback" };
  sources: string[];
  evidenceChunks?: string[];
};
type Evaluation={total:number;weights:{brandAlignment:number;originality:number;authenticity:number;policy:number};confidence:{score:number;level:string;basis:string};scores:{brandAlignment:number;originality:number;authenticity:number;policy:number|null};evidence:{brandMatchType:string;brandLexicalCoverage:number;brandMatches:{source:string;excerpt:string;similarity:number}[];competitorMatches:{name:string;url:string;reason:string;similarity:number;matchType?:string}[];clicheMatches:string[];policy:{applicable:boolean;forbidden:string[];preferred:string[];legalTextDetected:boolean}};insight:{strengths:string[];weaknesses:string[];improvements:string[]};method:string};

const steps = ["Assets", "Brand profile", "Competitors", "Knowledge base"];

export default function Home() {
  const input = useRef<HTMLInputElement>(null);
  const [files, setFiles] = useState<File[]>([]);
  const [url, setUrl] = useState("");
  const [status, setStatus] = useState<"idle" | "running" | "done" | "error">("idle");
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState("");
  const [phase2,setPhase2]=useState(false);
  const [phase3,setPhase3]=useState(false);
  const [lastEvaluation,setLastEvaluation]=useState<Evaluation|null>(null);
  const [backendOnline,setBackendOnline]=useState<boolean|null>(null);
  const stage = status === "done" ? 4 : status === "running" ? 2 : files.length || url ? 1 : 0;
  const totalSize = useMemo(() => files.reduce((sum, file) => sum + file.size, 0), [files]);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const params=new URLSearchParams(location.search);const saved=localStorage.getItem("branddna-phase1");if(saved){setResult(JSON.parse(saved));setStatus("done");if(params.has("phase2"))setPhase2(true);if(params.has("phase3"))setPhase3(true)}else if(params.has("phase2")||params.has("phase3")){setResult({profile:{name:"Mypakhi Demo",industry:"Organic bamboo menstrual care",audience:"Indian customers seeking comfortable sustainable period care",tone:["Clear","Human","Confident"],values:["Comfort","Sustainability","Freedom"],vocabulary:["Bamboo","Comfort","Care"],restricted:["Best-in-class","Revolutionary","Unlock potential"],summary:"Premium organic bamboo sanitary pads focused on rash-free comfort and sustainable menstrual care."},competitors:[{name:"Whisper",url:"https://www.whisperindia.com/",score:84,reason:"Sanitary pads focused on comfort and protection."},{name:"Carmesi",url:"https://www.carmesi.in/",score:82,reason:"Premium eco-friendly menstrual care products."}],evidenceChunks:["Pakhi creates ultra-soft organic bamboo sanitary pads for rash-free comfort, reliable protection and sustainable menstrual care."],stats:{pages:1,characters:1200,chunks:5,vectors:8},sources:["Demo brand guidelines"]});setStatus("done");setPhase2(params.has("phase2"));setPhase3(params.has("phase3"))}}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{let active=true;const check=()=>fetch("/api/architecture",{cache:"no-store"}).then(r=>r.json()).then(data=>{if(active)setBackendOnline(data.status==="ok"&&Boolean(data.services?.fastapi?.active)&&Boolean(data.services?.qdrant?.active))}).catch(()=>{if(active)setBackendOnline(false)});check();const timer=window.setInterval(check,15000);return()=>{active=false;window.clearInterval(timer)}},[]);

  function addFiles(list: FileList | null) {
    if (!list) return;
    setFiles((current) => [...current, ...Array.from(list)].slice(0, 6));
  }

  async function build() {
    if (!files.length && !url.trim()) return;
    setStatus("running"); setError(""); setResult(null);
    const form = new FormData();
    files.forEach((file) => form.append("files", file));
    form.append("url", url.trim());
    try {
      const response = await fetch("/api/onboard", { method: "POST", body: form });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Could not build your BrandDNA.");
      setResult(payload); localStorage.setItem("branddna-phase1",JSON.stringify(payload)); setStatus("done");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Something went wrong.");
      setStatus("error");
    }
  }

  function reset() { setFiles([]); setUrl(""); setResult(null); setStatus("idle"); setError(""); setPhase2(false); setPhase3(false); setLastEvaluation(null); localStorage.removeItem("branddna-phase1"); }

  return (
    <main className="min-h-screen bg-[#f6f7fb] text-[#151931]">
      <header className="border-b border-[#e6e8f0] bg-white/90 backdrop-blur">
        <div className="mx-auto flex h-20 max-w-[1240px] items-center justify-between px-6">
          <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#202a68] text-white"><Sparkles size={19}/></div><div><div className="font-serif text-xl font-bold tracking-tight">BrandDNA <span className="text-[#f36c21]">AI</span></div><div className="text-[10px] font-bold uppercase tracking-[.19em] text-[#7f849a]">Distinctiveness engine</div></div></div>
          <div className="flex items-center gap-2"><div className={`rounded-full border px-3 py-1.5 text-xs font-bold ${backendOnline===false?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}><span className={`mr-2 inline-block size-2 rounded-full ${backendOnline===false?"bg-red-500":"bg-emerald-500"}`}/>{backendOnline===null?"Checking AI backend…":backendOnline?"AI backend synced":"AI backend offline · fallback active"}</div><div className="rounded-full border border-[#dfe2ed] bg-[#f9f9fc] px-3 py-1.5 text-xs font-semibold text-[#666d86]">{phase3?"Phase 3 · Validation & improvement":phase2?"Phase 2 · Content scoring":"Phase 1 · Brand intelligence"}</div></div>
        </div>
      </header>

      <section className="mx-auto max-w-[1240px] px-6 py-12">
        {!phase2&&!phase3&&<div className="mb-10 flex flex-col justify-between gap-7 lg:flex-row lg:items-end">
          <div><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-[#f36c21]">Automated brand onboarding</p><h1 className="max-w-3xl font-serif text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Build your brand’s intelligence layer.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#656b82]">Turn guidelines, campaigns and a website into a structured brand profile, ranked competitor set and searchable knowledge-base blueprint.</p></div>
          <button onClick={reset} className="self-start text-sm font-semibold text-[#697088] hover:text-[#202a68]">Start over</button>
        </div>}

        {result&&<nav className="sticky top-3 z-20 mb-8 flex items-center gap-2 rounded-2xl border border-[#dde1eb] bg-white/95 p-2 shadow-lg backdrop-blur" aria-label="Phase navigation"><button onClick={()=>{setPhase2(false);setPhase3(false)}} className={`phase-tab ${!phase2&&!phase3?"phase-tab-active":""}`}><span>1</span>Brand intelligence</button><button onClick={()=>{setPhase2(true);setPhase3(false)}} className={`phase-tab ${phase2&&!phase3?"phase-tab-active":""}`}><span>2</span>Content scoring</button><button disabled={!lastEvaluation} onClick={()=>{if(lastEvaluation){setPhase3(true);setPhase2(false)}}} className={`phase-tab ${phase3?"phase-tab-active":""} disabled:cursor-not-allowed disabled:opacity-40`}><span>3</span>Validation & improvements</button></nav>}

        {!phase2&&!phase3&&<div className="mb-8 grid grid-cols-4 overflow-hidden rounded-2xl border border-[#e0e3ed] bg-white">
          {steps.map((label, index) => <div key={label} className={`relative flex items-center gap-3 border-r border-[#eceef4] p-4 last:border-r-0 ${index <= stage ? "text-[#202a68]" : "text-[#a4a8b8]"}`}><span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs font-bold ${index < stage || status === "done" ? "bg-[#202a68] text-white" : index === stage ? "bg-[#fff0e7] text-[#f36c21]" : "bg-[#f0f1f5]"}`}>{index < stage || status === "done" ? <Check size={14}/> : index + 1}</span><span className="hidden text-sm font-bold sm:block">{label}</span></div>)}
        </div>}

        <div key={phase3?"phase3":phase2?"phase2":"phase1"} className="phase-view">{!result ? <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
          <div className="rounded-3xl border border-[#e1e4ee] bg-white p-7 shadow-[0_12px_40px_rgba(24,31,75,.06)] sm:p-9">
            <div className="mb-7"><h2 className="font-serif text-2xl font-bold">Add your brand sources</h2><p className="mt-2 text-sm text-[#73798e]">PDF and plain-text files · up to 6 files · 10 MB each</p></div>
            <div onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();addFiles(e.dataTransfer.files)}} onClick={()=>input.current?.click()} className="group cursor-pointer rounded-2xl border-2 border-dashed border-[#cfd3e2] bg-[#fafbfe] px-6 py-11 text-center transition hover:border-[#f36c21] hover:bg-[#fffaf7]">
              <input ref={input} type="file" multiple accept=".pdf,.txt,.md" className="hidden" onChange={(e)=>addFiles(e.target.files)}/><div className="mx-auto mb-4 grid size-12 place-items-center rounded-2xl bg-[#fff0e7] text-[#f36c21]"><UploadCloud/></div><p className="font-bold text-[#202a68]">Drop guidelines or campaigns here</p><p className="mt-1 text-sm text-[#858a9c]">or click to browse files</p>
            </div>
            {files.length > 0 && <div className="mt-4 space-y-2">{files.map((file,i)=><div key={`${file.name}-${i}`} className="flex items-center gap-3 rounded-xl border border-[#e8eaf1] px-4 py-3"><FileText size={18} className="text-[#f36c21]"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.name}</p><p className="text-xs text-[#999dae]">{(file.size/1024).toFixed(0)} KB</p></div><button aria-label={`Remove ${file.name}`} onClick={(e)=>{e.stopPropagation();setFiles(files.filter((_,n)=>n!==i))}}><X size={16}/></button></div>)}</div>}
            <div className="my-6 flex items-center gap-4 text-xs font-bold uppercase tracking-[.16em] text-[#a0a4b2]"><span className="h-px flex-1 bg-[#e6e8ef]"/>and<span className="h-px flex-1 bg-[#e6e8ef]"/></div>
            <label className="text-sm font-bold">Brand website</label><div className="mt-2 flex items-center rounded-xl border border-[#dfe2eb] px-4 focus-within:border-[#202a68]"><Globe2 size={18} className="text-[#969bad]"/><input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://yourbrand.com" className="h-12 flex-1 bg-transparent px-3 text-sm outline-none"/></div>
            <div className="mt-5 flex items-start gap-3 rounded-xl border border-[#dfe4f3] bg-[#f7f8fc] p-4"><Search className="mt-0.5 shrink-0 text-[#202a68]" size={18}/><div><p className="text-sm font-bold text-[#202a68]">Competitors are discovered automatically</p><p className="mt-1 text-xs leading-5 text-[#73798e]">BrandDNA searches by category, product and audience, verifies official websites, then ranks only evidence-backed matches.</p></div></div>
            {error && <p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}
            <button disabled={(!files.length&&!url.trim())||status==="running"} onClick={build} className="mt-7 flex h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#202a68] px-5 font-bold text-white transition hover:bg-[#162052] disabled:cursor-not-allowed disabled:opacity-40">{status === "running" ? <><LoaderCircle className="animate-spin" size={19}/>Discovering and verifying brands…</> : <>Discover my competitive set <ArrowRight size={18}/></>}</button>
          </div>
          <aside className="rounded-3xl bg-[#202a68] p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff9d68]">What happens next</p><h3 className="mt-4 font-serif text-3xl font-bold">From raw assets to usable intelligence.</h3><div className="mt-8 space-y-6">{[[FileText,"Extract","Read and clean the source content."],[Sparkles,"Understand","Identify tone, values and vocabulary."],[Search,"Discover","Rank the closest competitors."],[Check,"Index","Create retrieval-ready chunks."]].map(([Icon,title,body],i)=>{const C=Icon as typeof FileText;return <div key={String(title)} className="flex gap-4"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-white/10"><C size={16}/></div><div><p className="font-bold">{i+1}. {String(title)}</p><p className="mt-1 text-sm leading-6 text-[#c4c9e4]">{String(body)}</p></div></div>})}</div><div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-[#cbd0e7]">This demo runs locally. Connect Claude, Tavily, Firecrawl and Qdrant through the existing service boundary for production.</div></aside>
        </div> : phase3&&lastEvaluation?<InsightPanel result={result} evaluation={lastEvaluation} onBack={()=>{setPhase3(false);setPhase2(true)}}/>:phase2?<EvaluationPanel result={result} onBack={()=>setPhase2(false)} evaluation={lastEvaluation} setEvaluation={setLastEvaluation} onValidate={()=>{setPhase3(true);setPhase2(false)}}/>:<Dashboard result={result} totalSize={totalSize} onEvaluate={()=>setPhase2(true)}/>}</div>
      </section>
    </main>
  );
}

function Dashboard({result,totalSize,onEvaluate}:{result:Result;totalSize:number;onEvaluate:()=>void}) {
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 rounded-3xl bg-[#202a68] p-7 text-white sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-full bg-emerald-400/20 text-emerald-300"><Check/></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#9ea6d4]">Knowledge base ready</p><h2 className="mt-1 font-serif text-3xl font-bold">{result.profile.name}</h2></div></div><div className="flex items-center gap-3"><div className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{result.stats.vectors} records · {result.stats.vectorBackend==="qdrant"?"Qdrant synced":"local fallback"}</div><button onClick={onEvaluate} className="rounded-full bg-[#f36c21] px-5 py-2 text-sm font-bold">Open Phase 2 →</button></div></div>
    <div className="grid gap-6 lg:grid-cols-[1.08fr_.92fr]">
      <section className="rounded-3xl border border-[#e0e3ed] bg-white p-7"><p className="section-label">Structured brand profile</p><p className="mt-5 text-lg leading-8 text-[#4f566d]">{result.profile.summary}</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Industry" value={result.profile.industry}/><Field label="Audience" value={result.profile.audience}/><Tags label="Tone of voice" items={result.profile.tone}/><Tags label="Core values" items={result.profile.values}/><Tags label="Preferred vocabulary" items={result.profile.vocabulary}/><Tags label="Restricted words" items={result.profile.restricted} orange/></div></section>
      <section className="rounded-3xl border border-[#e0e3ed] bg-white p-7"><div className="flex items-center justify-between"><p className="section-label">Verified competitive set</p><span className="text-xs font-semibold text-emerald-600">Automatic live discovery</span></div><div className="mt-5 space-y-3">{result.competitors.map((item,i)=><div key={item.url} className="rounded-2xl border border-[#e9ebf2] p-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-[#f0f2f8] text-xs font-bold text-[#202a68]">{i+1}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold">{item.name}</p><p className="truncate text-[11px] text-[#9a9eae]">{item.url}</p></div><p className="text-sm font-bold text-[#f36c21]">{item.score}% match</p></div><p className="mt-2 text-xs text-[#666d84]">{item.reason}</p></div></div></div>)}</div></section>
    </div>
    <div className="grid gap-4 sm:grid-cols-4">{[["Source data",`${Math.max(1,totalSize/1024).toFixed(0)} KB`],["Text extracted",`${result.stats.characters.toLocaleString()} chars`],["Retrieval chunks",result.stats.chunks],["Vector records",result.stats.vectors]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#e0e3ed] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#9ba0b0]">{label}</p><p className="mt-2 font-serif text-3xl font-bold text-[#202a68]">{value}</p></div>)}</div>
    <button onClick={onEvaluate} className="flex h-14 w-full items-center justify-center gap-2 rounded-xl bg-[#f36c21] font-bold text-white hover:bg-[#d95b15]">Continue to Phase 2 · Evaluate content <ArrowRight size={18}/></button>
  </div>
}

function EvaluationPanel({result,onBack,onValidate,evaluation,setEvaluation}:{result:Result;onBack:()=>void;onValidate:()=>void;evaluation:Evaluation|null;setEvaluation:(value:Evaluation|null)=>void}){
  const [content,setContent]=useState("");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [listening,setListening]=useState(false);
  const [liveTranscript,setLiveTranscript]=useState("");
  const recognitionRef=useRef<{stop:()=>void}|null>(null);
  function dictate(){
    type Recognition={lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((event:{results:ArrayLike<{0:{transcript:string};isFinal:boolean}>})=>void)|null;onerror:((event:{error?:string})=>void)|null;onend:(()=>void)|null};
    if(listening&&recognitionRef.current){recognitionRef.current.stop();return}
    const speechWindow=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
    const RecognitionCtor=speechWindow.SpeechRecognition||speechWindow.webkitSpeechRecognition;
    if(!RecognitionCtor){setError("Speech-to-text is not supported in this browser. Use Chrome or Edge.");return}
    const recognition=new RecognitionCtor();const startingText=content.trim();recognition.lang="en-IN";recognition.interimResults=true;recognition.continuous=false;recognitionRef.current=recognition;setListening(true);setLiveTranscript("");setError("");
    recognition.onresult=(event)=>{let finalText="";let interimText="";for(let i=0;i<event.results.length;i++){const text=event.results[i][0]?.transcript||"";if(event.results[i].isFinal)finalText+=`${text} `;else interimText+=text}const spoken=`${finalText}${interimText}`.trim();setLiveTranscript(interimText);if(spoken)setContent(`${startingText} ${spoken}`.trim())};
    recognition.onerror=(event)=>{setListening(false);recognitionRef.current=null;setError(event.error==="not-allowed"?"Microphone access was denied. Allow microphone permission in the browser address bar and try again.":"Speech recognition stopped before transcription completed. Please try again.")};recognition.onend=()=>{setListening(false);setLiveTranscript("");recognitionRef.current=null};recognition.start();
  }
  async function evaluate(){setBusy(true);setError("");try{const response=await fetch("/api/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,profile:result.profile,competitors:result.competitors,evidenceChunks:result.evidenceChunks})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setEvaluation(payload)}catch(reason){setError(reason instanceof Error?reason.message:"Evaluation failed.")}finally{setBusy(false)}}
  return <div className="space-y-6"><button onClick={onBack} className="text-sm font-bold text-[#687088]">← Back to knowledge base</button>
    {!evaluation?<><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-[#e0e3ed] bg-white p-8"><p className="section-label">Phase 2 · Content scoring</p><h2 className="mt-3 font-serif text-4xl font-bold">Score campaign copy.</h2><p className="mt-3 text-lg leading-8 text-[#6d7388]">Paste an ad, social caption, email or landing-page draft—or dictate it. Meaningless and highly repetitive input is rejected before scoring.</p><div className="relative mt-7"><textarea value={content} onChange={e=>setContent(e.target.value)} className="min-h-60 w-full rounded-2xl border border-[#dfe2eb] p-5 pr-20 text-lg leading-8 outline-none focus:border-[#202a68]" placeholder="Paste or dictate meaningful campaign content…"/><button onClick={dictate} type="button" className={`absolute bottom-4 right-4 grid size-12 place-items-center rounded-full text-white shadow-lg ${listening?"animate-pulse bg-red-500":"bg-[#f36c21]"}`} aria-label={listening?"Stop dictation":"Start dictation"} title={listening?"Stop dictation":"Speech to text"}>{listening?<X size={21}/>:<Mic size={21}/>}</button></div><p className="mt-2 text-sm text-[#7d8294]">{listening?`Listening… ${liveTranscript||"speak now"}. Tap the red button to stop.`:"Tap the microphone to dictate. Chrome or Edge will request microphone permission."}</p>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-600">{error}</p>}<button onClick={evaluate} disabled={busy||!content.trim()} className="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-xl bg-[#202a68] text-lg font-bold text-white disabled:opacity-40">{busy?<><LoaderCircle className="animate-spin" size={18}/>Validating and running four engines…</>:<>Calculate distinctiveness score <ArrowRight size={18}/></>}</button></section>
    <aside className="rounded-3xl bg-[#202a68] p-8 text-white"><h3 className="font-serif text-3xl font-bold">Four measurable signals.</h3><div className="mt-7 space-y-5">{[["Brand alignment","Similarity to the brand profile and vocabulary."],["Originality","Inverse overlap with competitor evidence."],["Authenticity","Explainable matches to generic AI clichés."],["Policy compliance","Forbidden and preferred-word checks."]].map(([a,b],i)=><div key={a} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white/10 text-xs font-bold">{i+1}</span><div><p className="font-bold">{a}</p><p className="mt-1 text-sm text-[#c5cae4]">{b}</p></div></div>)}</div></aside></div></>:<><EvaluationReport value={evaluation} onAgain={()=>setEvaluation(null)}/><button onClick={onValidate} className="mt-6 h-14 w-full rounded-xl bg-[#f36c21] text-lg font-bold text-white">Continue to Phase 3 · Validate score and improve →</button></>}</div>
}

function EvaluationReport({value,onAgain}:{value:Evaluation;onAgain:()=>void}){const cards:[[string,number|null],[string,number|null],[string,number|null],[string,number|null]]=[["Brand Alignment",value.scores.brandAlignment],["Originality",value.scores.originality],["Authenticity",value.scores.authenticity],["Policy Compliance",value.scores.policy]];const weightText=`${Math.round(value.weights.brandAlignment*100)}% alignment · ${Math.round(value.weights.originality*100)}% originality · ${Math.round(value.weights.authenticity*100)}% authenticity${value.weights.policy?` · ${Math.round(value.weights.policy*100)}% policy`:" · policy N/A"}`;return <div className="space-y-6"><section className="rounded-3xl bg-[#202a68] p-8 text-white"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff9d68]">Phase 2 · Scoring complete</p><h2 className="mt-3 font-serif text-4xl font-bold">Brand Distinctiveness Score</h2><p className="mt-3 text-base text-[#c6cbe3]">{weightText}</p><p className="mt-2 text-sm text-[#aeb5d8]">Estimate confidence: {value.confidence.level} ({value.confidence.score}%)</p></div><div className="grid size-36 place-items-center rounded-full border-8 border-[#f36c21] bg-white/5"><div className="text-center"><span className="font-serif text-5xl font-bold">{value.total}</span><p className="text-sm text-[#c6cbe3]">/ 100</p></div></div></div></section><div className="grid gap-4 sm:grid-cols-4">{cards.map(([label,score])=><div key={label} className="rounded-2xl border border-[#e0e3ed] bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#8d92a5]">{label}</p><p className="mt-3 font-serif text-4xl font-bold text-[#202a68]">{score===null?"N/A":`${score}%`}</p></div>)}</div><p className="rounded-2xl border border-[#dfe3ee] bg-white p-5 text-center text-base text-[#626980]">Scoring is complete. Continue to Phase 3 for detailed validation, retrieved evidence, confidence basis, and brand-specific improvements.</p><button onClick={onAgain} className="h-12 w-full rounded-xl border border-[#202a68] font-bold text-[#202a68]">Score another draft</button></div>}
function Evidence({title,items}:{title:string;items:string[]}){return <section className="rounded-3xl border border-[#e0e3ed] bg-white p-6"><p className="section-label">{title}</p><div className="mt-4 space-y-3">{items.map((item,i)=><div key={`${item}-${i}`} className="flex gap-3 rounded-xl bg-[#f7f8fc] p-3 text-sm leading-6"><span className="font-bold text-[#f36c21]">{i+1}</span><span>{item}</span></div>)}</div></section>}

function InsightPanel({result,evaluation,onBack}:{result:Result;evaluation:Evaluation;onBack:()=>void}){
  const topBrand=evaluation.evidence.brandMatches[0];const topRival=evaluation.evidence.competitorMatches[0];
  const validations=[
    {name:"Brand alignment",score:evaluation.scores.brandAlignment,why:topBrand?`Detected ${evaluation.evidence.brandMatchType} with ${evaluation.evidence.brandLexicalCoverage}% wording coverage; the closest semantic brand evidence matched at ${topBrand.similarity}%.`:"No approved brand evidence produced a strong match.",action:`Use concrete ${result.profile.name} language such as ${result.profile.vocabulary.slice(0,3).join(", ")}.`},
    {name:"Originality",score:evaluation.scores.originality,why:topRival?`${topRival.name} is the closest competitor at ${topRival.similarity}% (${topRival.matchType||"semantic overlap"}). Originality is based on the margin between brand evidence and competitor evidence.`:"No meaningful competitor overlap was retrieved.",action:topRival?`Avoid claims shared with ${topRival.name}; lead with a proprietary product detail, proof point or customer outcome.`:"Preserve the distinctive product-specific claims already present."},
    {name:"Authenticity",score:evaluation.scores.authenticity,why:evaluation.evidence.clicheMatches.length?`Matched generic AI-style phrases: ${evaluation.evidence.clicheMatches.join(", ")}. Each exact match reduces authenticity.`:"No exact phrases matched the explainable generic-AI phrase library.",action:evaluation.evidence.clicheMatches.length?"Replace motivational abstractions with a specific verb, product feature and measurable outcome.":"Keep the current specific, human phrasing."},
    {name:"Policy compliance",score:evaluation.scores.policy,why:!evaluation.evidence.policy.applicable?"No explicit forbidden-word or required-text policy was found in the submitted brand evidence, so this component is not scored.":evaluation.evidence.policy.forbidden.length?`Restricted language detected: ${evaluation.evidence.policy.forbidden.join(", ")}.`:`No restricted terms were found. Preferred terms used: ${evaluation.evidence.policy.preferred.join(", ")||"none"}.`,action:!evaluation.evidence.policy.applicable?"Upload explicit brand-policy rules to activate this score.":evaluation.evidence.policy.forbidden.length?`Remove ${evaluation.evidence.policy.forbidden.join(", ")} and use approved vocabulary instead.`:`Add relevant approved terms naturally where they strengthen clarity.`}
  ];
  const distinctMoves=[...evaluation.insight.improvements,`Anchor the opening in ${result.profile.values.slice(0,2).join(" and ").toLowerCase()} rather than a broad category promise.`,topRival?`Differentiate from ${topRival.name} by emphasizing evidence it does not own—specific material, packaging, process, guarantee or customer proof.`:"Add one proprietary proof point competitors cannot easily repeat.",`Use the preferred vocabulary—${result.profile.vocabulary.slice(0,4).join(", ")}—only where it describes a concrete benefit.`];
  return <div className="space-y-7"><button onClick={onBack} className="text-sm font-bold text-[#687088]">← Back to Phase 2 score</button><section className="rounded-3xl bg-[#202a68] p-8 text-white"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#ff9d68]">Phase 3 · Validation & improvement</p><h2 className="mt-3 font-serif text-4xl font-bold">Why the score is {evaluation.total}/100.</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-[#c9cee5]">Every conclusion below is tied to retrieved brand evidence, competitor similarity, matched generic phrases, or deterministic policy rules.</p><p className="mt-3 text-base font-bold text-[#ffbd98]">{evaluation.confidence.level} confidence · {evaluation.confidence.score}% — {evaluation.confidence.basis}</p></div><div className="grid size-32 shrink-0 place-items-center rounded-full border-8 border-[#f36c21]"><span className="font-serif text-5xl font-bold">{evaluation.total}</span></div></div></section>
  <section><p className="section-label">Component-by-component validation</p><div className="mt-5 grid gap-5 md:grid-cols-2">{validations.map(item=><article key={item.name} className="rounded-3xl border border-[#e0e3ed] bg-white p-6"><div className="flex items-center justify-between"><h3 className="font-serif text-2xl font-bold text-[#202a68]">{item.name}</h3><span className="rounded-full bg-[#eef0f7] px-4 py-2 font-bold text-[#202a68]">{item.score===null?"N/A":`${item.score}%`}</span></div><p className="mt-5 text-base leading-7 text-[#555d74]"><b>Why:</b> {item.why}</p><p className="mt-3 rounded-xl bg-[#fff5ef] p-4 text-base leading-7 text-[#8b421c]"><b>Improve:</b> {item.action}</p></article>)}</div></section>
  <div className="grid gap-6 lg:grid-cols-2"><Evidence title="Retrieved brand evidence" items={evaluation.evidence.brandMatches.map(x=>`${x.similarity}% similarity · ${x.excerpt}`)}/><Evidence title="Closest competitor evidence" items={evaluation.evidence.competitorMatches.map(x=>`${x.name} · ${x.similarity}% · ${x.reason}`)}/><Evidence title="Validated strengths" items={evaluation.insight.strengths.length?evaluation.insight.strengths:["No strong evidence-backed strengths were detected."]}/><Evidence title="Validated weaknesses" items={evaluation.insight.weaknesses.length?evaluation.insight.weaknesses:["No critical evidence-backed weaknesses were detected."]}/></div>
  <section className="rounded-3xl border border-[#f0d2c1] bg-[#fffaf7] p-7"><p className="section-label">Prioritized distinctiveness plan</p><div className="mt-5 grid gap-4 md:grid-cols-2">{[...new Set(distinctMoves)].filter(Boolean).map((item,i)=><div key={item} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#f36c21] font-bold text-white">{i+1}</span><p className="text-base leading-7 text-[#3f465c]">{item}</p></div>)}</div></section><p className="rounded-xl border border-[#e0e3ed] bg-white p-4 text-sm text-[#71778b]">Validation method: {evaluation.method}</p></div>
}

function Field({label,value}:{label:string;value:string}) { return <div><p className="field-label">{label}</p><p className="mt-2 font-semibold text-[#31374f]">{value}</p></div> }
function Tags({label,items,orange=false}:{label:string;items:string[];orange?:boolean}) { return <div><p className="field-label">{label}</p><div className="mt-2 flex flex-wrap gap-2">{items.map(item=><span key={item} className={`rounded-full px-3 py-1.5 text-xs font-bold ${orange?"bg-[#fff0e7] text-[#cc5312]":"bg-[#eef0f7] text-[#303a74]"}`}>{item}</span>)}</div></div> }
